"""Update Product

Revision ID: 65220be94be0
Revises: a38674101078
Create Date: 2024-05-03 15:29:08.261697

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '65220be94be0'
down_revision: Union[str, None] = 'a38674101078'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('Product_name_key', 'Product', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('Product_name_key', 'Product', ['name'])
    # ### end Alembic commands ###
